### ISSUE TITLE
Cannot have ambient Enums

### ISSUE THREAD

**Issue by keroserene** [freedomjs/freedom-typescript-api#8]
Enums in typescript should only be in actual `.ts` files.

There are currently a bunch of Enums declared, such as in `social.d.ts`. But the ambient context generates no javascript and therefore no actual values, so this isn't helpful. Defining them in the user program also does not work, as typescript then complains about duplicate identifiers.

One solution would be to have a separate `.ts` file to hold actual values, and have it compile to javascript which could be included separately in the user program.

**Comment by agallant** [comment]
Closing since this repo isn't maintained.
